"""Zrzuty ekranów: zgłoszenia do weryfikacji, gość, opóźnienie projektów, historia zmian (runda 3).
Użycie: python scripts/screenshots-v3.py http://127.0.0.1:3000 docs/screenshots — kod 1 przy błędach konsoli."""
import sys
from playwright.sync_api import sync_playwright

base = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:3000"
out = sys.argv[2] if len(sys.argv) > 2 else "docs/screenshots"
PW = "demo-cnc-2026"
errors = []


def ctx_page(b, mobile=False):
    if mobile:
        ctx = b.new_context(viewport={"width": 412, "height": 915}, device_scale_factor=2.625, is_mobile=True, has_touch=True, locale="pl-PL", timezone_id="Europe/Warsaw")
    else:
        ctx = b.new_context(viewport={"width": 1440, "height": 1000}, locale="pl-PL", timezone_id="Europe/Warsaw")
    page = ctx.new_page()
    page.on("console", lambda m: errors.append(f"{m.type}: {m.text}") if m.type == "error" and "status of 4" not in m.text else None)
    page.on("pageerror", lambda e: errors.append(f"pageerror: {e}"))
    return ctx, page


def login(page, user, pw=PW, wait=".rail"):
    page.goto(base + "/")
    page.fill("input[name=login]", user)
    page.fill("input[name=password]", pw)
    page.click("button[type=submit]")
    if wait:
        page.wait_for_selector(wait)


def shot(page, name, h=None, full=True, settle=500):
    if h is not None:
        page.goto(base + "/" + h)
    page.wait_for_timeout(settle)
    page.screenshot(path=f"{out}/{name}.png", full_page=full)


with sync_playwright() as p:
    b = p.chromium.launch()
    # Kierownik
    ctx, page = ctx_page(b)
    login(page, "kierownik")
    shot(page, "50-kierownik-zgloszenia", "#/zgloszenia")
    page.click("[data-racc]")
    page.wait_for_selector("dialog[open]")
    shot(page, "51-kierownik-przyjecie-odrobienia", full=False)
    page.click("dialog[open] [data-close]")
    shot(page, "52-projekty-opoznienie", "#/projekty")
    page.goto(base + "/#/projekty/PRJ-2026-0001")
    page.wait_for_selector("#loadHist")
    page.click("#loadHist")
    page.wait_for_timeout(600)
    shot(page, "53-projekt-historia")
    shot(page, "54-konta-gosc", "#/ustawienia?t=konta")
    shot(page, "55-historia-zmian", "#/ustawienia?t=historia", full=False)
    shot(page, "56-kierownik-dzisiaj", "#/dzisiaj")
    # Analiza (runda 6)
    shot(page, "67-analiza-miesiac", "#/analiza?t=miesiac&ym=2026-09", settle=900)
    shot(page, "68-analiza-rok", "#/analiza?t=rok&y=2026&c=2025&m=worked_min", settle=900)
    pid = page.evaluate("fetch('/api/projects?status=zakonczony').then(r => r.json()).then(l => l[l.length - 1].id)")
    page.goto(base + "/#/projekty/" + pid)
    page.wait_for_selector("#analysis", timeout=15000)
    page.wait_for_timeout(700)
    page.locator("#analysis").screenshot(path=f"{out}/69-przebieg-projektu.png")
    page.click("[data-reject-sim]")
    page.wait_for_selector("dialog[open]")
    page.fill("dialog[open] input[name=reason]", "inna technologia mocowania")
    page.click("dialog[open] button[type=submit]")
    page.wait_for_timeout(1200)
    page.wait_for_selector("#analysis", timeout=15000)
    page.click("#saveProjRep")
    page.wait_for_selector("dialog[open]")
    page.fill("dialog[open] textarea[name=note]", "Projekt zakończony przed terminem; godziny powyżej planu przez zmianę zakresu.")
    page.check("dialog[open] input[name=shared]")
    page.click("dialog[open] button[type=submit]")
    page.wait_for_timeout(700)
    page.goto(base + "/#/analiza?t=miesiac&ym=2026-09")
    page.wait_for_selector("#asave")
    page.click("#asave")
    page.wait_for_selector("dialog[open]")
    page.click("dialog[open] button[type=submit]")
    page.wait_for_timeout(700)
    shot(page, "70-zapisane-raporty", "#/analiza?t=raporty")
    rid = page.evaluate("fetch('/api/saved-reports').then(r => r.json()).then(l => l[l.length - 1].id)")
    shot(page, "71-raport-projektu", f"#/raport/{rid}", settle=900)
    page.emulate_media(media="print")
    shot(page, "72-raport-wydruk", f"#/raport/{rid}", settle=900)
    page.emulate_media(media="screen")
    # Plan pracy i tryby zmian / nadgodziny (runda 7–8)
    shot(page, "75-plan-pracy", "#/plan?data=2026-10-06", settle=800)
    shot(page, "76-kalendarz-nadgodziny", "#/kalendarz?tryb=tydzien&data=2026-10-05", settle=800)
    shot(page, "77-kalendarz-miesiac", "#/kalendarz?data=2026-10-01", settle=800)
    page.click(".cal button.chip.mode-wydluzona")
    page.wait_for_selector("dialog[open]")
    shot(page, "78-edycja-zmiany", full=False)
    page.click("dialog[open] [data-act=swap]")
    page.wait_for_selector("dialog[open] select[name=b_id]")
    shot(page, "79-zamiana-zmian", full=False)
    page.click("dialog[open] [data-close]")
    page.click("#bulkMode")
    page.wait_for_selector("dialog[open]")
    shot(page, "80-zmiana-trybu-pracy", full=False)
    page.click("dialog[open] [data-close]")
    page.click("#extraShift")
    page.wait_for_selector("dialog[open]")
    page.select_option("dialog[open] select[name=employee_id]", index=1)
    page.fill("dialog[open] input[name=work_date]", "2026-10-10")
    page.select_option("dialog[open] select[name=shift_template_id]", index=3)
    page.fill("dialog[open] input[name=reason]", "Termin ZL-26-0420")
    page.click("dialog[open] button[type=submit]")
    page.wait_for_timeout(900)
    if page.locator("dialog[open] .form-error").count() and page.locator("dialog[open] .form-error").inner_text().strip():
        errors.append("dzień dodatkowy: " + page.locator("dialog[open] .form-error").inner_text())
    shot(page, "81-analiza-nadgodziny", "#/analiza?t=miesiac&ym=2026-10", settle=900)
    page.goto(base + "/#/projekty/PRJ-2026-0002")
    page.wait_for_selector("#analysis", timeout=15000)
    page.wait_for_timeout(700)
    page.locator("#analysis .kpis").first.screenshot(path=f"{out}/82-projekt-w-nadgodzinach.png")
    # Powroty do projektu (poprawki po zakończeniu) — runda 9
    rp = page.evaluate("fetch('/api/projects?status=zakonczony').then(r => r.json()).then(l => (l.find(x => (x.returns || []).length) || {}).id)")
    if not rp:
        errors.append("brak projektu z powrotem w danych przykładowych")
    else:
        page.goto(base + "/#/projekty/" + rp)
        page.wait_for_selector("#analysis .rs-bar", timeout=15000)
        page.wait_for_timeout(600)
        shot(page, "84-projekt-z-poprawkami")
        page.locator(".rs-bar").first.scroll_into_view_if_needed()
        page.locator("#analysis").screenshot(path=f"{out}/85-czas-przed-i-po-poprawkach.png")
        page.click("#startRet")
        page.wait_for_selector("dialog[open]")
        shot(page, "86-powrot-do-projektu", full=False)
        page.click("dialog[open] [data-close]")
    shot(page, "87-analiza-miesiac-powroty", "#/analiza?t=miesiac&ym=2026-08", settle=900)
    shot(page, "88-kalendarz-urlopow", "#/absencje?t=kalendarz&m=2026-10&rok=2026", settle=900)
    shot(page, "89-kalendarz-urlopow-wrzesien", "#/absencje?t=kalendarz&m=2026-09&rok=2026", settle=900)
    shot(page, "91-pracownicy-urlopy", "#/pracownicy?rok=2026", settle=900)
    shot(page, "93-wyjscia-kalendarz", "#/wyjscia?m=2026-10", settle=900)
    shot(page, "95-zestawienia-lista", "#/analiza?t=zestawienia", settle=700)
    bid = page.evaluate("fetch('/api/report-bundles').then(r => r.json()).then(l => l[0].id)")
    shot(page, "96-zestawienie-dokument", f"#/zestaw/{bid}", settle=800)
    page.emulate_media(media="print")
    shot(page, "97-zestawienie-wydruk", f"#/zestaw/{bid}", settle=800)
    page.emulate_media(media="screen")
    shot(page, "98-zestawienie-edycja", f"#/zestaw/{bid}?edytuj=1", settle=900)
    ctx.close()
    ctx, page = ctx_page(b)
    login(page, "przelozony")
    shot(page, "73-przelozony-raporty", "#/analiza")
    for h in ["/api/analytics/month?ym=2026-09", "/api/analytics/year?year=2026"]:
        st = page.evaluate(f"fetch('{h}').then(r => r.status)")
        if st != 403:
            errors.append(f"przełożony ma dostęp do {h}: {st}")
    ctx.close()
    ctx, page = ctx_page(b, mobile=True)
    login(page, "kierownik", wait=".shell")
    shot(page, "74-telefon-analiza-miesiac", "#/analiza?t=miesiac&ym=2026-09", settle=900)
    shot(page, "83-telefon-kalendarz", "#/kalendarz?tryb=tydzien&data=2026-10-05", settle=800)
    shot(page, "90-telefon-kalendarz-urlopow", "#/absencje?t=kalendarz&m=2026-10&rok=2026", settle=900)
    shot(page, "92-telefon-pracownicy-urlopy", "#/pracownicy?rok=2026", settle=900)
    shot(page, "94-telefon-wyjscia-kalendarz", "#/wyjscia?m=2026-10", settle=900)
    ctx.close()
    # Pracownik — komputer i telefon
    ctx, page = ctx_page(b)
    login(page, "celina")
    shot(page, "57-pracownik-zglos", "#/zglos")
    shot(page, "58-pracownik-projekty-tylko-swoje", "#/projekty")
    shot(page, "66-pracownik-projekt-szczegoly", "#/projekty/PRJ-2026-0001")
    page.goto(base + "/#/projekty/PRJ-2026-0003")
    page.wait_for_timeout(600)
    if "Brak uprawnień" not in page.inner_text("main"):
        errors.append("pracownica widzi nieprzypisany projekt PRJ-2026-0003")
    ctx.close()
    ctx, page = ctx_page(b, mobile=True)
    login(page, "bartosz", wait=".shell")
    shot(page, "59-telefon-pracownik-dzisiaj", "#/dzisiaj")
    page.goto(base + "/#/zglos")
    page.wait_for_selector("[data-kind=spoznienie]")
    page.click("[data-kind=spoznienie]")
    page.fill("input[name=time_to]", "07:20")
    page.fill("textarea[name=note]", "Awaria samochodu")
    shot(page, "60-telefon-zglos-spoznienie", full=True)
    page.click("#reqF button[type=submit]")
    page.wait_for_timeout(800)
    shot(page, "61-telefon-po-wyslaniu")
    ctx.close()
    # Gość
    ctx, page = ctx_page(b)
    login(page, "gosc")
    shot(page, "62-gosc-status")
    page.click("details summary")
    shot(page, "63-gosc-etapy")
    ctx.close()
    ctx, page = ctx_page(b, mobile=True)
    login(page, "gosc", wait=".shell")
    shot(page, "64-telefon-gosc")
    ctx.close()
    # Blokada logowania
    ctx, page = ctx_page(b)
    for _ in range(6):
        login(page, "kierownik-test", pw="zle-haslo-123", wait=None)
        page.wait_for_timeout(250)
    shot(page, "65-blokada-logowania", full=False)
    ctx.close()
    b.close()

if errors:
    print("Błędy konsoli:")
    for e in errors:
        print("  " + e)
    sys.exit(1)
print("Brak błędów konsoli.")
